In [1]:
import numpy as np


In [ ]:
# Crear un array
arr = np.array([1, 2, 3, 4, 5]) # Crear un array de 1D
arr 

In [ ]:
# Operaciones básicas
# Suma 2 a cada elemento
print(arr + 2)  
# Multiplica cada elemento por 2
print(arr * 2)  

In [ ]:
# Crear una matriz
# Crear un array de 2D
matrix = np.array([[1, 2], [3, 4]]) 
matrix

In [ ]:
# Transponer una matriz
print(matrix.T)

In [ ]:
# Producto punto de dos vectores
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(np.dot(v1, v2))

Números uniformemente espaciados sobre un intervalo especificado.

In [ ]:
arr = np.linspace(0, 100, 10)
arr

Array reshaping

In [ ]:
# Crear un array de 10x10
arr = np.arange(100).reshape(10, 10) 
# Imprimir el array
print(arr) 
# Obtener la forma del array
arr.shape  

In [ ]:
# Crear un array de 2x5x10
arr = np.arange(100).reshape(2, 5, 10) 
# Imprimir el array
print(arr) 
# Obtener la forma del array
arr.shape 

**Ejercicio**
Crea una función que tome como entrada una matriz NumPy y un eje (axis) y devuelva la suma de los elementos a lo largo del eje especificado.


In [ ]:
# Solución

def suma_eje(matrix, axis): # Suma a lo largo de un eje
    return np.sum(matrix, axis=axis) # Suma a lo largo del eje especificado

# Ejemplo de uso
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(suma_eje(matrix, axis=0))  # Suma a lo largo de las columnas
print(suma_eje(matrix, axis=1))  # Suma a lo largo de las filas



In [6]:
arr = np.arange(16).reshape(4, 4) # Crear un array de 4x4
print(arr) # Imprimir el array
print(arr.sum()) # Suma de todos los elementos
print(arr.sum(axis=0)) # Suma sobre columnas
print(arr.sum(axis=1)) # Suma sobre filas


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
120
[24 28 32 36]
[ 6 22 38 54]


In [ ]:
# Máximo de todos los elementos
print(arr.max()) 
# Mínimo de todos los elementos
print(arr.min()) 
# Mínimo de cada fila
print(arr.min(axis=1)) 
# Mínimo de cada columna
print(arr.min(axis=0)) 

Arrays de 1 y 0

In [ ]:
arr = np.zeros(10) # Crear un array de 10 ceros
arr

In [ ]:
arr = np.ones(10) # Crear un array de 10 unos
arr

In [ ]:
arr = np.linspace(0, 100, 10) # Crear un array de 10 elementos entre 0 y 100
arr.std() # Calcular la desviación estándar

In [ ]:
arr_1 = np.array([1, 2, 3, 4, 6]) # Crear un array de 1D
arr_2 = np.arange(5) # Crear un array de 1D

np.add(arr_1, arr_2) # Sumar los dos arrays

Arrays aleatorios

In [ ]:
dice_samples = np.random.randint(1, 7, size=15)
dice_samples

In [18]:
# Crear un array de 7x4 con valores aleatorios entre 1 y 28 sin que se repitan

arr = np.random.choice(np.arange(1, 29), size=(7, 4), replace=False)
arr


array([[15, 27, 26,  6],
       [22, 24, 23, 13],
       [14, 19,  3,  4],
       [10, 11, 18, 21],
       [16, 20,  8,  1],
       [ 2, 12, 28,  9],
       [25,  5,  7, 17]])

In [22]:
dice_samples = np.random.choice(arr.flatten(), size=5) # Muestrear 5 elementos del array
dice_samples

array([10, 25, 16, 13, 20])